# Generated by Django 6.0 on 2025-12-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
